phrase:
  access_token: 0f65f474ec3065b92798f39fc361715d7015e163b65a61249deb8eaa317f6458
  project_id: 98f8a65a99043ae1a408ab5b54e462ef
  file_format: nested_json
  push:
    sources:
    - file: packages/common/src/assets/locales/en/about.json
      params:
        file_format: nested_json
        locale_id: a3816dbcc503951a36157b1c035897a3
        update_translations: true
  pull:
    targets:
    - file: packages/common/src/assets/locales/sv/about.json
      params:
        file_format: nested_json
        locale_id: 0513981fd258083b3fcde6a2bd5d7c9a
    - file: packages/common/src/assets/locales/ru/about.json
        params:
          file_format: nested_json
          locale_id: e080a869bc511a31a1e674a15e718b1b
