phrase:
  access_token: 0f65f474ec3065b92798f39fc361715d7015e163b65a61249deb8eaa317f6458
  project_id: 98f8a65a99043ae1a408ab5b54e462ef
  file_format: nested_json
  push:
    sources:
    - file: packages/common/src/assets/locales/en/<tag>.json
      params:
        locale_id: ed23519b2403fe8d69c53c3d786d3332
  pull:
    targets:
    # about
    - file: packages/common/src/assets/locales/<locale_name>/about.json
      params:
        tags: about
    # account
    - file: packages/common/src/assets/locales/<locale_name>/account.json
      params:
        tags: account
